name: WLogger
version: '1.0.0'
main: me.penguinx13.wLogger.WLogger
api-version: '1.19'
commands:
  wlogger:
    description: Main WLogger command
    usage: /<command>
permissions:
  wlogger.admin:
    description: Access to WLogger admin commands
    default: op

